env:
  CIRRUS_AGENT_VERSION: 1.26.0

task:
  name: windows mingw build
  env:
    CIRRUS_CLONE_DEPTH: 1
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
    cpu: 2
  build_script: ContinuousIntegration\winbuild_mingw.bat
  assemble_examples_script: ContinuousIntegration\winbuild_mingw_examples.bat
  assemble_tests_script: ContinuousIntegration\winbuild_mingw_tests.bat

task:
  name: windows Visual Studio 2019 build
  env:
    CIRRUS_CLONE_DEPTH: 1
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
    cpu: 2
  # FIXME: currently doesn't work, missing VSC compiler
  build_script: ContinuousIntegration\winbuild_vs2019.bat
  # exe is installed at the same location as the MinGW build does
  assemble_examples_script: ContinuousIntegration\winbuild_mingw_examples.bat
  assemble_tests_script: ContinuousIntegration\winbuild_mingw_tests.bat
